Repository eunomia-bpf/wasm-bpf, pull requests merged in 2023-05, with the labels that each got.

#107 add uprobe example
  examples/uprobe/Makefile
  examples/uprobe/README.md
  examples/uprobe/libbpf-wasm.h
  examples/uprobe/target.c
  examples/uprobe/uprobe.bpf.c
  examples/uprobe/uprobe.c
Labels: size/L

#115 fix terminating issue (again)
  runtime/wasm-bpf-rs/Cargo.toml
  runtime/wasm-bpf-rs/src/handle.rs
  runtime/wasm-bpf-rs/src/tests/mod.rs
Labels: size/S

#116 Add the c wrapper for APIs of `wasm-bpf`
  .github/workflows/build-static-wasm-bpf.yml
  Makefile
  runtime/Cargo.lock
  runtime/Cargo.toml
  runtime/c-wrapper/Cargo.toml
  runtime/c-wrapper/src/lib.rs
Labels: size/L

#113 add "#include <unistd.h>"
  examples/xdp/xdp.c
Labels: size/XS
