Repository eunomia-bpf/wasm-bpf, pull requests merged in 2023-03, with the labels that each got.

#45 example: adopted opensnoop example from bcc
  examples/opensnoop/Makefile
  examples/opensnoop/README.md
  examples/opensnoop/libbpf-wasm.h
  examples/opensnoop/opensnoop.bpf.c
  examples/opensnoop/opensnoop.c
  examples/opensnoop/opensnoop.h
  examples/opensnoop/trace_helpers.c
  examples/opensnoop/trace_helpers.h
Labels: size/XL

#47 [runtime] support passing arguments to Wasm program
  runtime/rust/src/main.rs
Labels: size/XS

#49 [doc] refactor chinese documents
  README.md
  README_zh.md
Labels: size/M

#50 [runtime] format and cleanup rust code
  runtime/rust/src/func/attach.rs
  runtime/rust/src/func/close.rs
  runtime/rust/src/func/fd_by_name.rs
  runtime/rust/src/func/load.rs
  runtime/rust/src/func/map_operate.rs
  runtime/rust/src/func/mod.rs
  runtime/rust/src/func/poll.rs
  runtime/rust/src/func/wrapper_poll.rs
  runtime/rust/src/main.rs
  runtime/rust/src/utils.rs
Labels: size/M

#51 [runtime] use the correct way to pass arguments
  runtime/rust/src/main.rs
Labels: size/XS

#52 [runtime] MIPS support for cpp runtime
  runtime/cpp/CMakeLists.txt
  runtime/cpp/third_party/vmlinux/mips/vmlinux.h
  runtime/cpp/third_party/vmlinux/mips/vmlinux_610.h
  runtime/cpp/third_party/vmlinux/powerpc/vmlinux.h
  runtime/cpp/third_party/vmlinux/powerpc/vmlinux_514.h
  runtime/cpp/third_party/vmlinux/riscv/vmlinux.h
  runtime/cpp/third_party/vmlinux/riscv/vmlinux_519.h
Labels: size/XXL

#54 Add licenses for the rust runtime
  runtime/rust/src/func/attach.rs
  runtime/rust/src/func/close.rs
  runtime/rust/src/func/fd_by_name.rs
  runtime/rust/src/func/load.rs
  runtime/rust/src/func/map_operate.rs
  runtime/rust/src/func/mod.rs
  runtime/rust/src/func/poll.rs
  runtime/rust/src/func/wrapper_poll.rs
  runtime/rust/src/log_format.rs
  runtime/rust/src/main.rs
  runtime/rust/src/state.rs
  runtime/rust/src/utils.rs
Labels: size/L, size/M

#55 [runtime] Fix possible memory error
  runtime/cpp/include/bpf-api.h
  runtime/cpp/src/main.cpp
  runtime/cpp/src/wasm-bpf.cpp
Labels: size/M

#67 Improve rust coverages
  README.md
  runtime/wasm-bpf-rs/src/lib.rs
  runtime/wasm-bpf-rs/tests/lsm.wasm
  runtime/wasm-bpf-rs/tests/opensnoop.wasm
  runtime/wasm-bpf-rs/tests/rust-bootstrap.wasm
  runtime/wasm-bpf-rs/tests/sockfilter.wasm
  runtime/wasm-bpf-rs/tests/sockops.wasm
Labels: size/XS

#68 [runtime] Add more tests for wasm runtime
  .github/workflows/c-cpp.yml
  .github/workflows/deploy-asserts.yml
  .github/workflows/rust.yml
  .gitignore
  Makefile
  examples/go-execve/README.md
  examples/go-execve/main.go
  runtime/wasm-bpf-rs/src/lib.rs
  runtime/wasm-bpf-rs/tests/go-execve.wasm
Labels: size/L

#71 Re-structure tests for cpp runtime
  .github/workflows/c-cpp.yml
  runtime/cpp/cmake/SourcesAndHeaders.cmake
  runtime/cpp/test/CMakeLists.txt
  runtime/cpp/test/asserts/.gitignore
  runtime/cpp/test/asserts/Makefile
  runtime/cpp/test/src/bpf_api_test.cpp
  runtime/cpp/test/src/maps_test.h
  runtime/cpp/test/src/memory_check_test_driver.cpp
  runtime/cpp/test/wasm-apps/.gitignore
  runtime/cpp/test/wasm-apps/Makefile
  runtime/cpp/test/wasm-apps/api.h
  runtime/cpp/test/wasm-apps/base64decode.h
  runtime/cpp/test/wasm-apps/binding.cpp
  runtime/cpp/test/wasm-apps/build.sh
  runtime/cpp/test/wasm-apps/memory_test_1.cpp
  runtime/cpp/test/wasm-apps/memory_test_2.cpp
Labels: size/L

#72 ci: avoid run some test on fork
  .github/workflows/deploy-asserts.yml
  .github/workflows/release-container.yml
  .github/workflows/rust.yml
Labels: size/XS

#76 Add lint check workflow & format all source files
  .clang-format
  .github/workflows/c-cpp-lint.yml
  examples/bootstrap/bootstrap.bpf.c
  examples/bootstrap/bootstrap.c
  examples/bootstrap/bootstrap.h
  examples/bootstrap/bootstrap.wasm.h
  examples/execve/execve.bpf.c
  examples/execve/execve.c
  examples/go-execve/execve.bpf.c
  examples/go-lsm/lsm.bpf.c
  examples/lsm/lsm.bpf.c
  examples/lsm/lsm.c
  examples/opensnoop/opensnoop.bpf.c
  examples/opensnoop/opensnoop.c
  examples/opensnoop/trace_helpers.c
  examples/opensnoop/trace_helpers.h
  examples/runqlat/bits.bpf.h
  examples/runqlat/core_fixes.bpf.h
  examples/runqlat/maps.bpf.h
  examples/runqlat/runqlat.bpf.c
  examples/runqlat/runqlat.c
  examples/runqlat/runqlat.h
  examples/runqlat/trace_helpers.c
  examples/runqlat/trace_helpers.h
  examples/rust-bootstrap/bootstrap.bpf.c
  examples/sockfilter/sockfilter.bpf.c
  examples/sockfilter/sockfilter.c
  examples/sockops/sockops.bpf.c
  examples/sockops/sockops.c
  runtime/cpp/include/bpf-api.h
  runtime/cpp/src/main.cpp
  runtime/cpp/src/wasm-bpf.cpp
  runtime/cpp/test/src/maps_test.h
  scripts/clang-format.unused
Labels: size/XXL

#77 Remove `clang-format.unused`
  scripts/clang-format.unused
Labels: size/S

#79 [runtime] add test for receiving output from a wasm module
  runtime/Cargo.lock
  runtime/wasm-bpf-rs/Cargo.toml
  runtime/wasm-bpf-rs/src/lib.rs
  runtime/wasm-bpf-rs/src/pipe.rs
  runtime/wasm-bpf-rs/src/tests/mod.rs
Labels: size/L

#85 [runtime] fix polling and runtime values
  runtime/cpp/src/wasm-bpf.cpp
Labels: size/M

#86 [doc] add crates.io badget
  README.md
Labels: size/XS

#89 Add support for user-registered host functions
  runtime/wasm-bpf-rs/src/runner.rs
  runtime/wasm-bpf-rs/src/tests/mod.rs
  runtime/wasm-bpf-rs/tests/custom_host_func.wasm
  runtime/wasm-bpf-rs/tests/custom_host_func/.gitignore
  runtime/wasm-bpf-rs/tests/custom_host_func/Makefile
  runtime/wasm-bpf-rs/tests/custom_host_func/README.md
  runtime/wasm-bpf-rs/tests/custom_host_func/custom_host_func.c
Labels: size/M

#94 [runtime] refactor runtime wasm-bpf-rs
  .github/workflows/c-cpp.yml
  Makefile
  README.md
  codecov.yaml
  docs/build.md
  examples/Makefile
  runtime/Cargo.lock
  runtime/Cargo.toml
  runtime/cli/Cargo.lock
  runtime/cli/Cargo.toml
  runtime/cli/Makefile
  runtime/cli/README.md
  runtime/cli/src/log_format.rs
  runtime/cli/src/main.rs
  runtime/wasm-bpf-rs/Cargo.toml
  runtime/wasm-bpf-rs/src/bpf/attach.rs
  runtime/wasm-bpf-rs/src/bpf/close.rs
  runtime/wasm-bpf-rs/src/bpf/fd_by_name.rs
  runtime/wasm-bpf-rs/src/bpf/load.rs
  runtime/wasm-bpf-rs/src/bpf/map_operate.rs
  runtime/wasm-bpf-rs/src/bpf/mod.rs
  runtime/wasm-bpf-rs/src/bpf/poll.rs
  runtime/wasm-bpf-rs/src/bpf/wrapper_poll.rs
  runtime/wasm-bpf-rs/src/handle.rs
  runtime/wasm-bpf-rs/src/lib.rs
  runtime/wasm-bpf-rs/src/pipe.rs
  runtime/wasm-bpf-rs/src/runner.rs
  runtime/wasm-bpf-rs/src/state.rs
  runtime/wasm-bpf-rs/src/tests/mod.rs
Labels: size/L

#96 Support exit code check
  runtime/wasm-bpf-rs/src/runner.rs
  runtime/wasm-bpf-rs/src/tests/mod.rs
  runtime/wasm-bpf-rs/tests/abnormal_exit.wasm
  runtime/wasm-bpf-rs/tests/exit_code/.gitignore
  runtime/wasm-bpf-rs/tests/exit_code/Makefile
  runtime/wasm-bpf-rs/tests/exit_code/README.md
  runtime/wasm-bpf-rs/tests/exit_code/abnormal_exit.c
  runtime/wasm-bpf-rs/tests/exit_code/long_sleep.c
  runtime/wasm-bpf-rs/tests/exit_code/normal_exit.c
  runtime/wasm-bpf-rs/tests/long_sleep.wasm
  runtime/wasm-bpf-rs/tests/normal_exit.wasm
Labels: size/M
